FEATURE: Add edit page for personal schedules
ucsb-cs156-w24/proj-courses-w24-5pm-3 pull request #21
Opened 2024-03-01 07:49 UTC by theanimated01

Closes #5 

Dev deployment: https://proj-courses-theanimated01-dev.dokku-07.cs.ucsb.edu

This PR adds the edit page feature for personal schedules where you can delete courses from the schedule page. Deleting a course from this page also deletes it from PSCourse Repository.

Changes made:

Backend:
1. Added a new delete mapping to delete a course by enroll code (enrollCd) and personal schedule id (psId). 
2. Also added tests for the new delete mapping

Frontend:
1. Created a new table called PersonalSectionsEditTable which has the delete button and functionality to delete a course
2. Added tests for this new table
3. Created a new utils file called CourseEditUtlis which is used to call the new delete mapping from the frontend
4. Added tests for this new utils file
5. Modified the placeholder PersonalSchedulesEditPage to contain the PersonalScheduleTable and the PersonalSectionsEditTable
6. Added tests for the modified edit page

Screenshots for before and after:
<img width="1440" alt="EditPage_before" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/assets/79371675/c8b9d057-645b-4418-a530-bcb21a512ffc">
<img width="1440" alt="EditPage_after" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/assets/79371675/d0703e01-2e19-4dab-b5ec-8f44e852eeb1">

2024-03-01 19:43 UTC, bwr02 approved these changes
LGTM
but it also seems like your implementation is more than 10 points 😭

2024-03-02 00:09 UTC, sophiattran requested changes

2024-03-02 00:09 UTC, sophiattran commented on .gitignore
You might not want to upload this file

2024-03-02 16:22 UTC, theanimated01 commented on .gitignore
i did that on purpose. i edited it to include .DS_store files that mac makes so that it's not accidentally pushed to the repo

2024-03-04 01:27 UTC, sophiattran approved these changes

2024-03-04 01:27 UTC, sophiattran commented on .gitignore
lgtm then!

2024-03-04 22:37 UTC, tallyhawley approved these changes
Looks good to me. Once this is merged, please stress to everyone that ALL active dev branches should be rebased on top of this commit due to the `prettier` changes, to resolve possible merge conflicts early on.

2024-03-05 02:50 UTC, Shakcmpsc approved these changes

2024-03-05 17:47 UTC, merged