Add more descriptive personal course page
ucsb-cs156-w24/proj-courses-w24-5pm-3 pull request #29
Opened 2024-03-06 01:44 UTC by bigjr-mkkong

This PR close issue #10 
[http://proj-course-michael-dev.dokku-07.cs.ucsb.edu](http://proj-course-michael-dev.dokku-07.cs.ucsb.edu)
![image](https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/assets/48128050/2406cb2a-b894-4d60-bf95-9e9262bc6fe3)

2024-03-06 06:11 UTC, chloeqta approved these changes, later dismissed
LGTM

2024-03-07 00:39 UTC, AnikaArora requested changes, later dismissed
Please add a small description in your PR. Also, add a "before" screenshot too so we can see exactly how your code changed the original version.

2024-03-07 23:25 UTC, bigjr-mkkong commented
> Please add a small description in your PR. Also, add a "before" screenshot too so we can see exactly how your code changed the original version.

I've updated my PR with a small description and before-after screenshots to clarify the changes I've made in this PR, please consider to merge.

2024-03-07 23:30 UTC, bwr02 approved these changes, later dismissed
LGTM

2024-03-07 23:31 UTC, tallyhawley commented on src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
> +    String quarter_QYY;
Why are we storing the quarter in QYY format? There is a helper on the frontend to convert from YYYYQ to QYY, just keep it in YYYYQ on the backend for consistency.

2024-03-08 02:57 UTC, bigjr-mkkong commented on src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
> +    String quarter_QYY;
Fixed it, please consider to merge into main branch

2024-03-08 04:09 UTC, bwr02 approved these changes
LGTM

2024-03-12 06:36 UTC, sophiattran approved these changes
lgtm

2024-03-13 00:27 UTC, tallyhawley approved these changes
Looks good to me:)

2024-03-13 00:34 UTC, merged