FEATURE: Add sections to personal schedule directly from search
ucsb-cs156-w24/proj-courses-w24-5pm-3 pull request #34
Opened 2024-03-07 08:23 UTC by theanimated01

Closes #7 

Dev deployment: https://proj-courses-theanimated01-dev.dokku-07.cs.ucsb.edu/

This PR adds a feature where you can directly add courses to a schedule from the courses search page.

Changes made:

1. Edited SectionTable.js to include a new modal when you press the Add Button
2. Edited SectionTableBase.js to include a column with the Add button. Add button only appears beside sections when a course is expanded. If a course does not have sections (i.e. not expandable) the Add button will appear beside the course
3. Modified the useBackend.js under utils so I could call that hook based on a boolean value. It was required otherwise the homepage would throw a error 403 (communicating with backend) as we are not signed in when we first open the home page and I used the backend call to populate the schedule dropdown in the modal. The boolean allowed me to call the useBackend function only when the modal was opened.
4. Edited test file for SectionTable

Screenshots for before and after:
<img width="1440" alt="Screenshot 2024-03-07 at 12 22 05 AM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/assets/79371675/962da11a-d90c-4c2b-ae6c-6b4df161a6e1">
<img width="1440" alt="Screenshot 2024-03-07 at 12 22 18 AM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/assets/79371675/7d6c84e0-7ab5-449e-8802-bc0ee886e00c">
<img width="1440" alt="Screenshot 2024-03-07 at 12 22 29 AM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/assets/79371675/afeffeaa-5e1c-46f5-ac2e-603823511cc7">

2024-03-07 17:37 UTC, bwr02 approved these changes, later dismissed
LGTM. Amazing guys great work

2024-03-07 19:42 UTC, chloeqta submitted a review, later dismissed
LGTM

2024-03-07 21:35 UTC, AnikaArora requested changes
Overall, looks great! One small issue is that when you're adding a class that doesn't have a section, the "add" button doesn't look like a button because its background really blends into the cell's color. Could you please edit the UI to made it look more like a button? When the class has a section, it's very clear since there's a color contrast but here it's very blended. 

Also, please add a screenshot of the "after" for a class that doesn't have a section too (once you fix this UI thing)!

2024-03-07 23:36 UTC, bwr02 approved these changes, later dismissed
LGTM

2024-03-08 00:06 UTC, tallyhawley commented on frontend/src/main/components/SectionsTableBase.js
> +                            ? "#7baacb"
Is it possible to change the color of the button instead of changing the table colors?

2024-03-08 02:00 UTC, theanimated01 commented on frontend/src/main/components/SectionsTableBase.js
> +                            ? "#7baacb"
Done. changed color of button instead of table

2024-03-08 02:08 UTC, sophiattran approved these changes
lgtm!

2024-03-08 02:09 UTC, bwr02 approved these changes
LGTM

2024-03-08 02:11 UTC, AnikaArora approved these changes
LGTM!

2024-03-08 02:14 UTC, merged